### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by neel-dey** [BaochangZhang/PSSS_registration#1]
Hi @BaochangZhang , 

The paper looks really interesting -- will its code be released soon?

Thanks,
Neel

**Comment by BaochangZhang** [comment]
Hi Neel, Thanks for you attention!  
Now,  DiffDeepDRR part is available, including a demo for registration.
Recently, we are busy developing an improved version, but the complete code will be released as soon as possible.
Bests,
Baochang
